### ISSUE TITLE
undoable feature

### ISSUE THREAD

**Issue by otomatik** [pardom/redux-kotlin#17]
Hi @pardom, first thanks for you amazing lib!
I was wondering if you planned to add a built-in "undoable" feature to this lib (or creating a dedicated one) like described [here](http://redux.js.org/docs/recipes/ImplementingUndoHistory.html) for instance?
Thanks again,
Thomas

**Comment by otomatik** [comment]
@pardom if not planned, do you have any clue on how I could implement an enhancer which return a different state object than the reducer enhanced?
Thanks,
Thomas

**Comment by pardom-zz** [comment]
@otomatik undo would be implemented as reducer enhancer. Since Kotlin is statically typed and JS is dynamically typed, we have to do things a bit differently. Here is some pseudocode of what the API might look like.

```kotlin
val undoReducer = createUndoReducer(getVanillaReducer())
val store = createStore(undoReducer, createInitialState(), createStoreEnhancer())

store.dispatch(Action.Increment)
undoReducer.undo()
```

**Comment by pardom-zz** [comment]
So far I've only ported the middlewares that we've needed in production. When the need for something arrises, I will generally find the best middleware for our needs and create a direct port. In the case of undo, it seems that this library is the most used? 

https://github.com/omnidan/redux-undo

If you need undo, I'd take a run at porting that. I've been considering creation of a redux-kotlin Github org and migrating all the redux projects I've authored. This would facilitate a central org for anyone to expand the Kotlin Redux ecosystem. In this case, I'd be happy to accept your contributions.

**Comment by otomatik** [comment]
@pardom thanks for your answers and your pseudocode :)
Indeed the langages differences lead to a different undoable API.
I would love to help in the redux-undo port even if I'm quite new to Kotlin and Redux (it would be a nice way to learn both of them).
Let me know if you decide to move your redux libraries to a dedicated organization.
Thanks again,
Thomas
